/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBanner: typeof import('./src/components/AppBanner.vue')['default']
    BaseDataTable: typeof import('./src/components/BaseDataTable.vue')['default']
    BaseEntityForm: typeof import('./src/components/BaseEntityForm.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InstrumentForm: typeof import('./src/components/InstrumentForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
  }
}
