INSERT INTO location (name) VALUES
    ('Fordson High School'),
    ('Dearborn High School'),
    ('Edsel Ford High School'),
    ('Salina Intermediate'),
    ('Bryant Middle School'),
    ('Stout Middle School'),
    ('O.L. Smith Middle School'),
    ('Lowrey School'),
    ('Maples Elementary'),
    ('Henry Ford Elementary'),
    ('McCollough-Unis School'),
    ('Becker Elementary'),
    ('DuVall Elementary'),
    ('Howe School'),
    ('River Oaks Elementary');

INSERT INTO student (first_name, last_name) VALUES
    ('Amina', 'Hassan'),
    ('David', 'Nguyen'),
    ('Sofia', 'Martinez'),
    ('Liam', 'Patel'),
    ('Noah', 'Khan'),
    ('Emma', 'Ali'),
    ('Olivia', 'Hussein'),
    ('Elijah', 'Jackson'),
    ('Isabella', 'Tran'),
    ('James', 'Baker'),
    ('Mia', 'Rahman'),
    ('Lucas', 'Chowdhury'),
    ('Benjamin', 'Alavi'),
    ('Charlotte', 'Farhat'),
    ('Ethan', 'Omar'),
    ('Harper', 'Abdullah'),
    ('Alexander', 'Salameh'),
    ('Amelia', 'Yousef'),
    ('Daniel', 'Hussein'),
    ('Layla', 'Karim');
